id: I11646728
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:11:26+00:00'
last_modified: '2022-06-08T01:27:39.272238+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ901
  title: བློ་རིག་གི་རྣམ་གཞག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B83B:
      image_group_id: I1CZ964
      title: ''
      total_pages: 60
      order: 1
      base_file: B83B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
