id: P004491
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ901
  title: བློ་རིག་གི་རྣམ་གཞག་
  author: ''
  volumes:
    007bf26bba444a5bab2552b28314bd24:
      image_group_id: I1CZ964
      title: ''
      volume_number: 1
      total_pages: 60
