id: P004491
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:26:33.206924
source_metadata:
  id: bdr:W1CZ901
  title: བློ་རིག་གི་རྣམ་གཞག་
  author: ''
  volumes:
    007bf26bba444a5bab2552b28314bd24:
      image_group_id: I1CZ964
      title: ''
      volume_number: 1
      total_pages: 60
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
